accounts/urls.py
from django.urls import path
from .views import (LoginView, SignupView, LogoutView, 
                    api_login, api_signup, set_avatar, view_profile, send_verification_email_api, 
                    edit_profile, update_profile, update_password_get, update_password_api, verify_user,
                    send_recovery_email_api, reset_password_get, forgot_password_get, reset_password_api)

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name="user_login_get"),
    path('api/login', api_login, name="user_login_post"),
    path('logout/', LogoutView.as_view(), name="user_logout"),
    path('signup/', SignupView.as_view(), name="user_signup_get"),
    path('api/verify/sendmail', send_verification_email_api, name="send_verification_email_api"),
    path('verify/<uidb64>/<token>', verify_user, name="verify_user"),
    path('recovery', forgot_password_get, name="forgot_password_get"),
    path('api/recovery/sendmail', send_recovery_email_api, name="send_recovery_email_api"),
    path('recovery/<uidb64>/<token>', reset_password_get, name="reset_password_get"),
    path('api/recovery/setpassword/<uidb64>/<emailb64>', reset_password_api, name="reset_password_api"),
    path('profile/<int:pk>', view_profile, name="view_profile"),
    path('profile/update', update_profile, name="update_profile_api"),
    path('profile/update/password', update_password_get, name="update_password_get"),
    path('profile/api/update/password', update_password_api, name="update_password_api"),
    path('profile/edit', edit_profile, name="edit_profile"),
    path('api/signup', api_signup, name="user_signup_post"),
    path('profile/avatar/set', set_avatar, name="set_avatar"),
]
   

classroom/urls.py
from django.urls import path, include
from .views import *
app_name = 'classroom'

urlpatterns = [
    path('', starter_homepage, name='starter'),
    path('classes', ClassesDashboard.as_view(), name="homepage"), # it's actually classes homepage, requires authentication
    path('classroom/new', create_classroom, name="create_classroom"),
    path('classroom/api/', include("classroom.api.urls")),
    path('classroom/<str:pk>', ClassroomDetail.as_view(), name="classroom_detail"),
    path('classroom/<str:pk>/connections', ClassroomConnections.as_view(), name="classroom_connections"),
    path('classroom/<str:pk>/rankings', ClassroomRanking.as_view(), name="classroom_ranking"),
    path('classroom/<str:pk>/assessment/create', create_assessment, name="create_assessment"),
    path('classroom/<str:pk>/assessment', view_assessment, name="view_assessment"),
    path('classroom/<str:cls_pk>/assessment/<int:pk>', view_student_assessment, name="view_student_assessment"),
    path('classroom/<str:pk>/assessment/printf', view_assessment_printf, name="view_assessment_printf"),
    path('classroom/<str:cls_pk>/assessments/download/excel', download_assessment_excel, name="download_assessment_excel"),
    path('classroom/<str:pk>/about', ClassroomAbout.as_view(), name="classroom_about"),
    path('classroom/<str:pk>/assignment/new', create_assignment, name="create_assignment"),
    path('classroom/<str:pk>/edit', edit_classroom, name="edit_classroom"),
    path('classroom/join/<str:cls_code>', join_classroom, name="join_classroom"),
    # topics
    path('classroom/<str:pk>/topics/<str:topic_id>', topic_posts, name="topic_posts"),
    # posts
    path('classroom/<str:pk>/post', create_post, name="post_to_classroom"),
    path('classroom/post/<str:pk>', PostDetail.as_view(), name="post_detail"),
    path('classroom/post/<str:pk>/edit', edit_post, name="edit_post"),
    path('classroom/post/<str:pk>/newfile', uploadPostFile, name="uploadPostFile"),
    path('classroom/post/<str:pk>/delete', delete_post, name="delete_post"),
    # assignment
    path('classroom/<str:pk>/assignments', classroom_assignment, name="view_classroom_assignment"),
    path('classroom/assignment/<str:pk>', view_assignment, name="view_assignment"),
    # students
    path('classroom/<str:pk>/students', classroom_students, name="classroom_students"),
    path('classroom/<str:pk>/groups', classroom_groups, name="classroom_groups"),
    # files
    path('classroom/<str:pk>/files', classroom_files, name="classroom_files"),
    # tasks
    path('classroom/<str:cls_pk>/task/', include("tasks.urls")),
]
   

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('classroom.urls')),
    # weeklies
    path('weeklies/', include('weeklies.urls')),
    path('weeklies/test/', include('weekly_test.urls')),
    path('weeklies/test/api/', include('weekly_test.api.urls')),
    # auth
    path('account/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from tasks import views
app_name = 'tasks'

# <included from classroomn.urls> url: classroom/<str:cls_pk>/task/

urlpatterns = [
    path('new', views.create_task, name="create_task"),
    path('<str:pk>', views.TaskDetail.as_view(), name="view_task"),
    path('<str:pk>/delete', views.delete_task_get, name="delete_task_get"),
    path('<str:pk>/api/delete', views.delete_task, name="delete_task_api"),
    path('files/<int:pk>', views.view_task_file, name="view_task_file"),
    path('work/<str:pk>', views.WorkDetail.as_view(), name="view_work"),
    path('<str:pk>/upload_work', views.upload_work, name="upload_work"),
    path('work/files/<int:pk>', views.view_work_file, name="view_work_file"),
    path('work/<str:pk>/changesubmission', views.change_work_submission_status, name="change_work_submission_status"),
    path('work/<str:pk>/delete', views.delete_work, name="delete_work"),
    path('work/<str:pk>/marking', views.update_work_score, name="update_work_score"),
    path('work/<str:pk>/remarks', views.update_work_remarks, name="update_work_remarks"),
]
   

accounts/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, render, get_object_or_404
from django.http import JsonResponse
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.urls import reverse
from django.core.mail import EmailMessage
from django.conf import settings
from .models import Account
from .utils import compress_image, check_account_data, check_user_data
from email.message import EmailMessage
from email.utils import formataddr
import ssl
import smtplib
from classroom.views import render_info_or_error



def send_html_email(receiver, subject, body):
    sender = settings.EMAIL_HOST_USER
    password = settings.EMAIL_HOST_PASSWORD
    host = settings.EMAIL_HOST
    port = settings.EMAIL_PORT
    
    em = EmailMessage()
    em['From'] = formataddr(("FlippedClassroom", sender))
    em['To'] = receiver
    em['Subject'] = subject
    em.set_content(body, subtype='html')
    
    context = ssl.create_default_context()

    with smtplib.SMTP_SSL(host, port, context=context) as smtp:
        smtp.login(sender, password)
        smtp.sendmail(sender, receiver, em.as_string())
    

def send_verification_email(request, user):
    current_site = get_current_site(request)
    email_subject = "Verify Your Email"
    receiver = user.email
    uid = urlsafe_base64_encode(force_bytes(user.id))
    token = default_token_generator.make_token(user)
    verification_url = request.build_absolute_uri(reverse("accounts:verify_user", args=(uid, token)))
    email_body = render_to_string('accounts/verification_mail.html', context={
        "user": user,
        "verification_url": verification_url,
    })
    send_html_email(receiver, email_subject, email_body)
    


class LoginView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("classroom:homepage")
        else:
            return render(request=request, template_name='accounts/login.html')


class SignupView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("classroom:homepage")
        else:
            return render(request=request, template_name='accounts/signup.html')

            
class LogoutView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            logout(request)
        return redirect("classroom:starter")
    
@login_required
def view_profile(request, pk):
    account = get_object_or_404(Account, pk=pk)
    return render(request, 'accounts/user_profile.html', context={'account':account})

@login_required
def edit_profile(request):
    account = request.user.account
    return render(request, 'accounts/user_edit_profile.html', context={'account':account})

@login_required
def update_password_get(request):
    return render(request, 'accounts/user_update_password.html')

@api_view(['POST'])
def api_login(request):
    # performs login through an api
    user = authenticate(username=request.data['email'], password=request.data['password'])
    if user:
        login(request, user)
        return Response({'status':'logged in'}, status=status.HTTP_200_OK)
    else:
        return Response({'status':'login failed'}, status=status.HTTP_401_UNAUTHORIZED)


@api_view(['POST'])
def api_signup(request):
    email = request.data['email']
    user_queryset = User.objects.filter(email=email)
    if len(user_queryset) > 0:
        return Response({'status':'email used'}, status=status.HTTP_400_BAD_REQUEST)
    try:
        user = User(
            username = request.data['email'],
            email = request.data['email'],
            first_name = request.data['first_name'],
            last_name = request.data['last_name']
        )
        user.set_password(request.data['password'])
        user.save()
        account_kwargs = {}
        account_kwargs['user'] = user
        is_student = request.data['is_student']
        account_kwargs['is_student'] = is_student
        if is_student:
            account_kwargs['institution'] = request.data['institution']
            account_kwargs['institutional_id'] = request.data['institutional_id'] 
        Account.objects.create(**account_kwargs)
    except Exception as e:
        return Response({'status':str(e)}, status=status.HTTP_406_NOT_ACCEPTABLE)
    login(request, user=user)
    return Response({'status':"complete"}, status=status.HTTP_201_CREATED)



@login_required
def verify_user(request, uidb64, token):
    try :
        user_id = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=user_id)
    except Exception as e:
        user = None
    
    if user and default_token_generator.check_token(user, token):
        account = user.account
        account.is_email_verified = True
        account.save()
        return render_info_or_error(request, "Verified", "Your email is successfully verified. You can return to dashboard")
    else:
        return render_info_or_error(request, "Error", "Invalid verification link", "error")


    

@api_view(["POST"])
@permission_classes([IsAuthenticated])
def update_profile(request):
    # firstly checking email is used or not
    user_qs = User.objects.filter(email=request.data['user_data']['email'])
    if len(user_qs) > 0:
        if user_qs[0] != request.user:
            return Response(status=status.HTTP_400_BAD_REQUEST)
    user_data = request.data['user_data']
    account_data = request.data['account_data']
    
    user = request.user
    account = user.account
    previous_mail = user.email
    
    try:
        check_user_data(user_data)
        check_account_data(account_data, request)
        for attr, val in user_data.items():
            setattr(user, attr, val)
        user.save()
        for attr, val in account_data.items():
            setattr(account, attr, val)
        if previous_mail != user.email:
            account.is_email_verified = False
        account.save()
    except Exception as e:
        return Response(status=status.HTTP_406_NOT_ACCEPTABLE)
    return Response(status=status.HTTP_200_OK)

@csrf_exempt
def set_avatar(request):
    if request.method == "POST":
        if len(request.FILES) > 0:
            user = request.user
            account = Account.objects.get(user=user)
            try:
                image_file = request.FILES.get('dp')
                compressed_image = compress_image(image_file)
            except ValidationError as e:
                return JsonResponse(data={'info': e.message}, status=400)
            if account.profile_picture is not None:
                account.profile_picture.delete(save=True)
            try:
                account.profile_picture = compressed_image
                account.save()
            except Exception as e:
                return JsonResponse(data={'info': 'Cannot save image'}, status=400)

            return JsonResponse({'status':'profile picture set'})
        

@api_view(["GET"])
@permission_classes([IsAuthenticated])
def send_verification_email_api(request):
    try:
        send_verification_email(request, request.user)
        return Response(status=status.HTTP_200_OK)
    except Exception as e:
        return Response(status=status.HTTP_503_SERVICE_UNAVAILABLE)        

     
@api_view(["POST"])
@permission_classes([IsAuthenticated])
def update_password_api(request):
    username = request.user.username
    try:
        current_pass = request.data['current_password']
        new_pass = request.data['new_password']
    except KeyError:
        return Response(status=status.HTTP_400_BAD_REQUEST)
    user_obj = authenticate(username=username, password=current_pass)
    if user_obj != None and user_obj==request.user:
        user_obj.set_password(new_pass)
        user_obj.save()
        logout(request)
        return Response(status=status.HTTP_202_ACCEPTED)
    else:
        return Response(status=status.HTTP_401_UNAUTHORIZED)
    

def forgot_password_get(request):
    return render(request, 'accounts/forgot.html')


@api_view(["POST"])
def send_recovery_email_api(request):
    email_subject = "Password Recovery"
    try:
        email = request.data['email']
    except Exception as e:
        return Response(data={"error":"no email provided"}, status=status.HTTP_400_BAD_REQUEST)
    user_qs = User.objects.filter(email=email)
    if len(user_qs) == 0:
        return Response(data={'info':'no user found with this email'}, status=status.HTTP_404_NOT_FOUND)
    user = user_qs[0]
    if not hasattr(user, 'account'):
        return Response(data={"info":"user has no account"}, status=status.HTTP_409_CONFLICT)

    uid = urlsafe_base64_encode(force_bytes(user.id))
    token = default_token_generator.make_token(user)
    recovery_url = request.build_absolute_uri(reverse("accounts:reset_password_get", args=(uid, token)))
    email_body = render_to_string('accounts/recovery_mail.html', context={
        "user": user,
        "recovery_url": recovery_url
    })
    try:
        send_html_email(user.email, email_subject, email_body)
    except Exception as e:

accounts/templates/accounts/login.html
<!DOCTYPE html> {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'accounts/styles/auth.css' %}">
    <title>FlippedClassroom Login</title>
</head>
<body>
    <div class="container login">
        <div class="form login-form">
            <div class="heading">
                <div class="site-title">Flipped Classroom</div>
            </div>
            {% csrf_token %}
            <div class="field-container inset-float-textinput email">
                <input class="inp_input" type="email" id="email" placeholder=" ">
                <label class="inp_label" for="email">Email</label>
            </div>
            <div class="field-container inset-float-textinput password">
                <input class="inp_input" type="password" id="password" placeholder=" ">
                <label class="inp_label" for="password">Password</label>
                <i class='bx bx-hide password-toggle' id="p1-toggle" data-inp="password"></i>
            </div>
            <div class="field-container submit">
                <div class="error-info" id="error-info-container" style="display: none;">
                    <i class='bx bx-info-circle'></i><span id="error-info-text"></span>
                </div>
                <button class="btn-1" id="submit">Login</button>
            </div>
            <div class="links">
                <div><a href="{% url 'accounts:user_signup_get' %}">Sign up</a></div>
                <div><a href="{% url 'accounts:forgot_password_get' %}">Forgot password?</a></div>
            </div>
        </div>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<script src="{% static 'accounts/scripts/login.js' %}"></script>

<script>
    $(document).ready(
        $("#email").focus()
    )
    const success_url = "{% url 'classroom:homepage' %}"
    const login_url = "{% url 'accounts:user_login_post' %}"
</script>
</body>
</html>

accounts/templates/accounts/recovery_mail.html
<!DOCTYPE html>
<html lang="en">
<body>
    {% autoescape off %}
    <h3>Hi, {{user.account.user_first_name}}</h3>
    <p>Please click the link below to reset your password</p>
    <p><a href="{{recovery_url}}">{{recovery_url}}</a></p>
    {% endautoescape %}
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html> {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'accounts/styles/auth.css' %}">
    <title>FlippedClassroom Signup</title>
</head>
<body>
    <div class="container signup mb-4">
        <div class="form">
            <div class="heading">
                <div class="site-title">Flipped Classroom</div>
            </div> {% csrf_token %}
            <div class="field-container name">
                <div class="first_name inset-float-textinput">
                    <input class="inp_input" type="text" id="first_name" placeholder=" ">
                    <label class="inp_label" for="first_name">First Name</label>
                </div>
                <div class="last_name inset-float-textinput">
                    <input class="inp_input" type="text" id="last_name" placeholder=" ">
                    <label class="inp_label" for="last_name">Last Name</label>
                </div>
            </div>
            
            <div class="field-container inset-float-textinput email">
                <input class="inp_input" type="email" id="email" placeholder=" ">
                <label class="inp_label" for="email">Email</label>
            </div>
            <div class="field-container inset-float-textinput password">
                <input class="inp_input" type="password" id="password1" placeholder=" ">
                <label class="inp_label" for="password1">Password</label>
                <i class='bx bx-hide password-toggle' id="p1-toggle" data-inp="password1"></i>
            </div>
            <div class="field-container inset-float-textinput password">
                <input class="inp_input" type="password" id="password2" placeholder=" ">
                <label class="inp_label" for="password2">Retype Password</label>
                <i class='bx bx-hide password-toggle' id="p2-toggle" data-inp="password2"></i>
            </div>
            <div class="actype-info">
                <i class='bg bx bxs-user-detail'></i>
                <div class="actype-con">
                    <div class="label me-2">I am a</div>
                    <div class="inp-con">
                        <div class="inp-inner me-2">
                            <input type="radio" name="actype" id="actype-student" checked="">
                            <label for="actype-student">Student</label>
                        </div>
                        <div class="inp-inner">
                            <input type="radio" name="actype" id="actype-teacher">
                            <label for="actype-teacher">Teacher</label>
                        </div>
                    </div>
                </div>
                <div class="field-container institution inset-float-textinput mt-3" id="inst-name-con" style="display: none">
                    <input class="inp_input" type="text" id="institution" placeholder=" ">
                    <label class="inp_label" for="institution">Institution</label>
                </div>
                <div class="field-container institution inset-float-textinput" id="inst-id-con" style="display: none">
                    <input class="inp_input" type="text" id="inst-id" placeholder=" ">
                    <label class="inp_label" for="inst-id">Institutional ID</label>
                </div>
            </div>
            <div class="field-container input-file">
                <input type="file" class="input-img" id="dp">
                <label for="dp"><i class='bx bx-image-add' ></i><span>Select avatar</span></label>
                <div class="selected-file" id="selected-file">No file selected</div>
            </div>
            <div class="field-container submit">
                <div class="error-info" id="error-info-container" style="display: none;"><i class='bx bx-info-circle'></i><span id="error-info-text"></span></div>
                <div class="signup-info" id="signup-info" style="display: none;"></div>
                <button class="btn-1" id="submit">Sign Up</button>
            </div>
            <div class="login-info">
                <span>Have an account?</span><a href="{% url 'accounts:user_login_get' %}">Login here</a>
            </div>
        </div>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<script src="{% static 'accounts/scripts/signup.js' %}"></script>
<script>
    const signup_url = "{% url 'accounts:user_signup_post' %}"
    const avatar_set_url = "{% url 'accounts:set_avatar' %}"
    const success_url = "{% url 'classroom:homepage' %}"
</script>
</body>
</html>

accounts/templates/accounts/user_edit_profile.html
{% extends 'classroom/base.html' %}
{% block style %} {% load static %}
<link rel="stylesheet" href="{% static 'accounts/styles/user_profile.css' %}">
<link rel="stylesheet" href="{% static 'classroom/styles/navbar.css' %}">
{% endblock style %}
{% block title %}<title>Edit profile</title>{% endblock title %}

{% block content %}
<div class="profile-edit-main">
    <div class="edit-profile-con bg-white container mt-4 shadow p-4">
        <div class="info mt-2 mb-3">
            <div class="dp" style="background-image: url('{{account.avatar_url}}');"></div>
            <div class="heading-con">
                <div class="heading">Edit Your Profile</div>
                <div class="update-pass-con">
                    <i class='bx bx-key'></i>
                    <a href="{% url 'accounts:update_password_get' %}">Update Password</a>
                </div>
            </div>
        </div>
        <div class="inp-con">
            <div class="first_name inset-float-textinput mb-3">
                <input class="inp_input" type="text" id="first_name" placeholder=" ">
                <label class="inp_label" for="first_name">First Name</label>
            </div>
            <div class="last_name inset-float-textinput mb-3">
                <input class="inp_input" type="text" id="last_name" placeholder=" ">
                <label class="inp_label" for="last_name">Last Name</label>
            </div>
            <div class="field-container institution inset-float-textinput mb-3">
                <input class="inp_input" type="text" id="institution" placeholder=" ">
                <label class="inp_label" for="institution">Institution</label>
            </div>
            {% if account.is_student %}
            <div class="field-container inset-float-textinput inst-id mb-3">
                <input class="inp_input" type="text" id="inst-id" placeholder=" ">
                <label class="inp_label" for="inst-id">Institutional ID</label>
            </div>
            {% endif %}
            <div class="field-container inset-float-textinput email mb-3">
                <input class="inp_input" type="email" id="email" placeholder=" ">
                <label class="inp_label" for="email">Email</label>
            </div>
            <div class="field-container input-file">
                <input type="file" class="input-img" id="dp">
                <label for="dp"><i class='bx bx-image-add' ></i><span>Select avatar</span></label>
                <div class="selected-file" id="selected-file">No file selected</div>
            </div>
            <div class="field-container submit">
                <div class="error-info" id="error-info-container" style="display: none;"><i class='bx bx-info-circle'></i><span id="error-info-text"></span></div>
                <div class="loader" id="loader-con" style="display: none;">
                    <div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
                </div>
                <button class="btn-1 shadow-sm" id="submit-btn">Save Changes</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'accounts/scripts/edit_profile.js' %}"></script>
<script>
    function setPrevVal() {
        $("#first_name").val('{{ account.user.first_name }}');
        $("#last_name").val('{{ account.user.last_name }}');
        {% if account.is_student %}
        $("#institution").val('{{ account.institution }}');
        $("#inst-id").val('{{ account.institutional_id }}');
        {% else %}
            {% if account.institution %}
            $("#institution").val('{{ account.institution }}');
            {% endif %}
        {% endif %}
        $("#email").val('{{ account.user.email }}');
    }
    $('main').addClass("")
    setTimeout(setPrevVal, 500);
    const update_profile_api = "{% url 'accounts:update_profile_api' %}";
    const avatar_set_url = "{% url 'accounts:set_avatar' %}"
    const csrftoken = "{{csrf_token}}";
</script>
{% endblock script %}

accounts/templates/accounts/user_update_password.html
{% extends 'classroom/base.html' %}
{% block style %} {% load static %}
<link rel="stylesheet" href="{% static 'accounts/styles/user_profile.css' %}">
<link rel="stylesheet" href="{% static 'classroom/styles/navbar.css' %}">
{% endblock style %}
{% block title %}<title>Update password</title>{% endblock title %}

{% block content %}
<div class="edit-profile-con container bg-white mt-4 shadow-lg p-4">
    <div class="info mt-2 mb-3">
        <div class="heading-con">
            <div class="heading">Update password</div>
        </div>
    </div>
    <div class="inp-con">
        <div class="first_name inset-float-textinput mb-3" id="current_pass_con">
            <input class="inp_input" type="text" id="current_password" data-parentid="current_pass_con" placeholder=" ">
            <label class="inp_label" for="current_password">Current password</label>
        </div>
        <div class="last_name inset-float-textinput mb-3" id="new_pass_con">
            <input class="inp_input" type="password" id="new_password" data-parentid="new_pass_con" placeholder=" ">
            <label class="inp_label" for="new_password">New password</label>
        </div>
        <div class="field-container institution inset-float-textinput mb-3" id="new_pass_repeat_con">
            <input class="inp_input" type="password" id="new_pass_repeat" data-parentid="new_pass_repeat_con" placeholder=" ">
            <label class="inp_label" for="new_pass_repeat">Retype new password</label>
        </div>
        
        <div class="field-container submit">
            <div class="error-info" id="error-info-container" style="display: none;"><i class='bx bx-info-circle'></i><span id="error-info-text"></span></div>
            <button class="btn-1 shadow-sm" id="update-pass-btn">Update</button>
        </div>
    </div>
</div>
{% endblock content %}


{% block script %}
<script src="{% static 'accounts/scripts/update_pass.js' %}"></script>
<script>
    const update_password_api = "{% url 'accounts:update_password_api' %}";
    const csrftoken = "{{csrf_token}}";
    const login_url = "{% url 'accounts:user_login_get' %}"
</script>
{% endblock script %}

accounts/templates/accounts/verification_mail.html
<!DOCTYPE html>
<html lang="en">
<body>
    {% autoescape off %}
    <h3>Hi {{user.account.user_first_name}}, welcome to Flipped Classroom</h3>
    <p>Please click the link below to verify your email</p>
    <p><a href="{{verification_url}}">{{verification_url}}</a></p>
    {% endautoescape %}
</body>
</html>