classroom/urls.py
from django.urls import path, include
from .views import *
app_name = 'classroom'

urlpatterns = [
    path('', starter_homepage, name='starter'),
    path('classes', ClassesDashboard.as_view(), name="homepage"), # it's actually classes homepage, requires authentication
    path('classroom/new', create_classroom, name="create_classroom"),
    path('classroom/api/', include("classroom.api.urls")),
    path('classroom/<str:pk>', ClassroomDetail.as_view(), name="classroom_detail"),
    path('classroom/<str:pk>/connections', ClassroomConnections.as_view(), name="classroom_connections"),
    path('classroom/<str:pk>/rankings', ClassroomRanking.as_view(), name="classroom_ranking"),
    path('classroom/<str:pk>/assessment/create', create_assessment, name="create_assessment"),
    path('classroom/<str:pk>/assessment', view_assessment, name="view_assessment"),
    path('classroom/<str:cls_pk>/assessment/<int:pk>', view_student_assessment, name="view_student_assessment"),
    path('classroom/<str:pk>/assessment/printf', view_assessment_printf, name="view_assessment_printf"),
    path('classroom/<str:cls_pk>/assessments/download/excel', download_assessment_excel, name="download_assessment_excel"),
    path('classroom/<str:pk>/about', ClassroomAbout.as_view(), name="classroom_about"),
    path('classroom/<str:pk>/assignment/new', create_assignment, name="create_assignment"),
    path('classroom/<str:pk>/edit', edit_classroom, name="edit_classroom"),
    path('classroom/join/<str:cls_code>', join_classroom, name="join_classroom"),
    # topics
    path('classroom/<str:pk>/topics/<str:topic_id>', topic_posts, name="topic_posts"),
    # posts
    path('classroom/<str:pk>/post', create_post, name="post_to_classroom"),
    path('classroom/post/<str:pk>', PostDetail.as_view(), name="post_detail"),
    path('classroom/post/<str:pk>/edit', edit_post, name="edit_post"),
    path('classroom/post/<str:pk>/newfile', uploadPostFile, name="uploadPostFile"),
    path('classroom/post/<str:pk>/delete', delete_post, name="delete_post"),
    # assignment
    path('classroom/<str:pk>/assignments', classroom_assignment, name="view_classroom_assignment"),
    path('classroom/assignment/<str:pk>', view_assignment, name="view_assignment"),
    # students
    path('classroom/<str:pk>/students', classroom_students, name="classroom_students"),
    path('classroom/<str:pk>/groups', classroom_groups, name="classroom_groups"),
    # files
    path('classroom/<str:pk>/files', classroom_files, name="classroom_files"),
    # tasks
    path('classroom/<str:cls_pk>/task/', include("tasks.urls")),
]
   

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('classroom.urls')),
    # weeklies
    path('weeklies/', include('weeklies.urls')),
    path('weeklies/test/', include('weekly_test.urls')),
    path('weeklies/test/api/', include('weekly_test.api.urls')),
    # auth
    path('account/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from tasks import views
app_name = 'tasks'

# <included from classroomn.urls> url: classroom/<str:cls_pk>/task/

urlpatterns = [
    path('new', views.create_task, name="create_task"),
    path('<str:pk>', views.TaskDetail.as_view(), name="view_task"),
    path('<str:pk>/delete', views.delete_task_get, name="delete_task_get"),
    path('<str:pk>/api/delete', views.delete_task, name="delete_task_api"),
    path('files/<int:pk>', views.view_task_file, name="view_task_file"),
    path('work/<str:pk>', views.WorkDetail.as_view(), name="view_work"),
    path('<str:pk>/upload_work', views.upload_work, name="upload_work"),
    path('work/files/<int:pk>', views.view_work_file, name="view_work_file"),
    path('work/<str:pk>/changesubmission', views.change_work_submission_status, name="change_work_submission_status"),
    path('work/<str:pk>/delete', views.delete_work, name="delete_work"),
    path('work/<str:pk>/marking', views.update_work_score, name="update_work_score"),
    path('work/<str:pk>/remarks', views.update_work_remarks, name="update_work_remarks"),
]
   

weeklies/urls.py
from django.urls import path, include
from .views import weeklyDetail, addFiles, downloadFile, edit_post, edit_weekly_view, delete_weekly_view

app_name = "weeklies"

# 'weeklies/' --->

urlpatterns = [
    path('<str:cls_pk>/api/', include('weeklies.api.urls')),
    path('<str:cls_pk>/week/<int:weeknum>', view=weeklyDetail, name='weeklydetail'),
    path('week/<str:pk>/edit', view=edit_weekly_view, name='edit_weekly'),
    path('week/<str:pk>/delete', view=delete_weekly_view, name='delete_weekly'),
    path('<str:weekly_pk>/file/upload', view=addFiles, name='uploadweeklyfiles'),
    path('<str:weekly_pk>/post/<int:pk>/edit', view=edit_post, name='edit_post'),
    path('<str:weekly_pk>/file/<int:pk>/download', view=downloadFile, name='downloadweeklyfile')
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from os.path import join, basename
from pathlib import Path
import uuid
from classroom.models import Classroom
from weeklies.models import Weekly


class Task(models.Model):
    def get_uuid():
        return uuid.uuid4().hex

    id = models.CharField(
        max_length=50,
        primary_key = True,
        default = get_uuid,
        editable = False,
    )

    title = models.CharField(max_length=250)
    marks = models.IntegerField(default=100)
    instruction = models.CharField(max_length=1000, null=True, blank=True)
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    weekly = models.ForeignKey(Weekly, null=True, blank=True, on_delete=models.CASCADE)
    preclass = models.BooleanField(default=False)
    inclass = models.BooleanField(default=False)
    postclass = models.BooleanField(default=False)
    addded = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField()

    def __str__(self):
        return f"{self.classroom.name} - Task"
    @property
    def is_ongoing(self):
        if self.deadline >= timezone.now():
            return True
        else:
            return False
        
    @property
    def is_group_task(self):
        return bool(self.group_set.count())
    
    @property
    def is_weekly_task(self):
        if self.weekly == None:
            return False
        else:
            return True
        
    @property
    def weekly_section(self):
        if self.is_weekly_task:
            if self.preclass:
                return "PreClass"
            elif self.inclass:
                return "InClass"
            elif self.postclass:
                return "PostClass"
            else:
                return "Weekly General"
        else:
            return "General"
        
    @property
    def section_icon_css(self):
        if self.preclass:
            return "bx bxs-left-arrow"
        elif self.inclass:
            return "bx bxs-square"
        elif self.postclass:
            return "bx bxs-right-arrow"
        else:
            return "bx bx-question-mark"
        
    @property
    def weeknum_str(self):
        return f"week {self.weekly.weeknum}"
    
    @property
    def task_type_ico_css(self):
        if self.is_group_task:
            return 'bx bx-group'
        else:
            return 'bx bx-briefcase'


class TaskAttachment(models.Model):
    def filepath(self, filename):
        return join("attachments", str(self.task.classroom.id), 'tasks', str(self.task.id), filename)

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    attached_file = models.FileField(upload_to=filepath, max_length=1000)

    @property
    def filename(self):
        name_str = basename(self.attached_file.name)
        return name_str.replace('_', ' ')
    
    @property
    def css_class(self):
        css_classes = {
            ".pdf": "bx bxs-file-pdf",
            ".pptx":"bx bx-slideshow",
            ".jpg": "bx bxs-file-image",
            ".png": "bx bxs-file-image",
            ".docx": "bx bxs-file-doc",
            ".zip": "bx bxs-file-archive",
            ".txt": "bx bxs-file-txt",
            ".py": "bx bxl-python",
            ".pyw": "bx bxl-python"
        }
        file_extention = Path(self.filename).suffix
        if file_extention in css_classes:
            return css_classes[file_extention]
        else:
            return "bx bxs-file-blank"


class Group(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    members = models.ManyToManyField(User)
    
    @property
    def work_submitted(self):
        qs = self.work_set.filter(is_submitted=True)
        return bool(len(qs))
    
    @property
    def work(self):
        qs = self.work_set.all()
        if len(qs) > 0:
            return qs[0]
        else:
            return False

    @property
    def submitted_work(self):
        qs = self.work.filter(is_submitted=True)[0]


class Work(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    submission_by = models.ForeignKey(User, on_delete=models.CASCADE)
    is_submitted = models.BooleanField(default=False)
    group = models.ForeignKey(Group, null=True, blank=True, on_delete=models.CASCADE)
    score = models.IntegerField(null=True, blank=True)
    remarks = models.CharField(max_length=1000, null=True, blank=True)
    submission_time = models.DateTimeField(null=True, blank=True)
    
    @property
    def is_late(self):
        if self.submission_time > self.task.deadline:
            return True
        else:
            return False
    
    @property
    def attachments(self):
        return self.workattachment_set.all()
    
    @property
    def num_attachments(self):
        return self.attachments.count()
    
    @property
    def time_css(self):
        if self.is_late:
            return "late"
        else:
            return ""
    

class WorkAttachment(models.Model):
    def filepath(self, filename):
        return join("attachments", str(self.work.task.classroom.id), 'tasks', str(self.work.task.id), 'submissions', filename)

    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    attached_file = models.FileField(upload_to=filepath, max_length=1000)

    @property
    def filename(self):
        name_str = basename(self.attached_file.name)
        return name_str.replace('_', ' ')
    
    @property
    def css_class(self):
        css_classes = {
            ".pdf": "bx bxs-file-pdf",
            ".pptx":"bx bx-slideshow",
            ".jpg": "bx bxs-file-image",
            ".png": "bx bxs-file-image",
            ".docx": "bx bxs-file-doc",
            ".zip": "bx bxs-file-archive",
            ".txt": "bx bxs-file-txt",
            ".py": "bx bxl-python",
            ".pyw": "bx bxl-python"
        }
        file_extention = Path(self.filename).suffix
        if file_extention in css_classes:
            return css_classes[file_extention]
        else:
            return "bx bxs-file-blank"

tasks/templates/tasks/delete_task.html
{% extends 'classroom/base.html' %}
{% block style %} {% load static %}
<link rel="stylesheet" href="{% static 'weeklies/styles/weekly.css' %}">
<link rel="stylesheet" href="{% static 'classroom/styles/navbar.css' %}">
{% endblock style %}
{% block title %}<title>Delete task</title>{% endblock title %}
{% block nav %}
<ul class="navbar-nav mb-2 mb-lg-0">
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="{% url 'classroom:classroom_detail' task.classroom.id %}">Dashboard</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_connections' task.classroom.id %}">Participants</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_ranking' task.classroom.id %}">Ranking</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:view_assessment' task.classroom.id %}">Assessment</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_about' task.classroom.id %}">About</a>
  </li>
</ul>
{% endblock nav %}


{% block content %}
<div class="edit-weekly">
  <div class="home-links">
    <a href="{% url 'classroom:classroom_detail' task.classroom.id %}">{{task.classroom.name|truncatechars:15}}</a>
    <i class='bx bxs-chevron-right' ></i>
    <a class="current" href="{% url 'weeklies:weeklydetail' task.classroom.id task.weekly.weeknum %}">Week {{task.weekly.weeknum}}</a>
  </div>
  <div class="info-con shadow-lg">
    <i class='bg bx bx-briefcase-alt-2' ></i>
    <div class="info-text">Are you sure to delete this Task and all the data associated with it?</div>
  </div>
  <div class="action">
    <a href="{% url 'classroom:tasks:view_task' task.classroom.id task.id %}" class="ico-btn btn btn-secondary"><i class='bx bx-chevrons-left'></i><span>Go Back</span></a>
    <button id="delete-btn" class="ico-btn btn btn-danger"><i class='bx bx-trash-alt'></i><span>Delete</span></button>
  </div>
</div>
{% endblock content %}


{% block script %}
<script src="{% static 'tasks/scripts/delete_task.js' %}"></script>
<script>
  const task_delete_url = "{% url 'classroom:tasks:delete_task_api' task.classroom.id task.id  %}";
  const weekly_url = "{% url 'weeklies:weeklydetail' task.classroom.id task.weekly.weeknum %}";
  const csrftoken = "{{csrf_token}}";
</script>
{% endblock script %}

tasks/templates/tasks/view_task.html
{% extends 'classroom/base.html' %}
{% block style %} {% load static %}
<link rel="stylesheet" href="{% static 'tasks/styles/viewtask.css' %}">
<link rel="stylesheet" href="{% static 'classroom/styles/navbar.css' %}">
<link rel="stylesheet" href="{% static 'classroom/styles/commons.css' %}">
{% endblock style %}
{% block title %}<title>View Task</title>{% endblock title %}
{% block nav %}
<ul class="navbar-nav mb-2 mb-lg-0">
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="{% url 'classroom:classroom_detail' task.classroom.id %}">Dashboard</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_connections' task.classroom.id %}">Participants</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_ranking' task.classroom.id %}">Ranking</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:view_assessment' task.classroom.id %}">Assessment</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_about' task.classroom.id %}">About</a>
  </li>
</ul>
{% endblock nav %}
{% block content %}
<div class="view-task-container {% if is_teacher %}teacher{% else %}student{% endif %}">
  <div class="left-col">
    {% if task.is_weekly_task %}
    <div class="home-links">
      <a href="{% url 'classroom:classroom_detail' task.classroom.id %}">{{task.classroom.name}}</a>
      <i class='bx bxs-chevron-right' ></i>
      <a href="{% url 'weeklies:weeklydetail' task.classroom.id task.weekly.weeknum %}">Week {{task.weekly.weeknum}}</a>
      <i class='bx bxs-chevron-right' ></i>
      <a class="current" >{{task.weekly_section}}</a>
    </div>
    {% endif %}
    <div class="task-info">
      <div class="task-title">{{ task.title }} {% if is_teacher %}<a href="{% url 'classroom:tasks:delete_task_get' task.classroom.id task.id %}"><i class='bx bx-trash-alt'></i></a>{% endif %} </div>
      <div class="task-meta-info">
        {% if task.is_group_task %}
        <div class="task-type-group task-type">
          <i class='bx bxs-group'></i>
          <span>Group Task</span>
        </div>
        {% else %}
        <div class="task-type-indiv task-type">
          <i class='bx bx-user'></i>
          <span>Individual Task</span>
        </div>
        {% endif %}
        <div class="points">
          <i class='bx bxs-coin-stack'></i>
          <span class="point">{{ task.marks }}</span><span class="label">Points</span>
        </div>
        <div class="deadline">
          <i class='bx bx-time'></i>
          <span class="time" id="task{{task.id}}-deadline">{{ task.deadline|date:"c" }}</span>
        </div>
      </div>
      <div class="task-instruction">
        {% if task.instruction %}
        <div class="instruction-text px-3 py-2 shadow-sm bg-white rounded">{{ task.instruction }}</div>
        {% endif %}
        <div class="attachments">
          {% for file in task.taskattachment_set.all %}
          <a href="{% url 'classroom:tasks:view_task_file' file.task.classroom.id file.id %}" class="attachment-item">
            <i class='{{ file.css_class }}'></i>
            <div class="filename">{{ file.filename|truncatechars:20 }}</div>
          </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="right-col">
    {% if is_teacher %}
    <div class="submissions">
      <div class="title">Submissions</div>
      <div class="contents">
        {% for group in group_submissions  %}
        <a href="{% url 'classroom:tasks:view_work' group.work.task.classroom.id group.work.id %}">
          <div class="submission">
            <div class="info">
              <div class="score">
                {% if group.work.score %}
                <div class="score-con">
                  <i class='bx bx-trophy'></i>
                  <div class="points"><span class="point">{{ group.work.score }}</span>Points</div>
                </div>
                {% else %}
                <div class="unchecked">Unchecked</div>
                {% endif %}
              </div>
              <div class="submit-time {% if group.work.is_late %}done-late{% endif %}">
                <i class='bx bx-timer'></i>
                <span class="time" id="work{{group.work.id}}-submit-time">{{ group.work.submission_time|date:'c' }}</span>
              </div>
            </div>
            
            <div class="num-attachments"><span class="num">{{ group.work.num_attachments }}</span>Attachment{{ group.work.num_attachments |pluralize }}</div>
            <div class="group-members">
              <div class="title">Group Members</div>
              <ul>
                {% for member in group.members.all %}
                <li>
                  <div class="dp" style="background-image: url('{{ member.account.avatar_url }}')">
                  </div>
                  <div class="name">{{ member.account.user_full_name }}</div>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </a>
        {% endfor %}
        {% for indiv_work in indiv_submissions  %}
        <a href="{% url 'classroom:tasks:view_work' indiv_work.task.classroom.id indiv_work.id %}">
          <div class="submission">
            <div class="info">
              <div class="score">
                {% if indiv_work.score %}
                <div class="score-con">
                  <i class='bx bx-trophy'></i>
                  <div class="points"><span class="point">{{ indiv_work.score }}</span>Points</div>
                </div>
                {% else %}
                <div class="unchecked">Unchecked</div>
                {% endif %}
              </div>
              <div class="submit-time {% if indiv_work.is_late %}done-late{% endif %}">
                <i class='bx bx-timer'></i>
                <span class="time" id="work{{indiv_work.id}}-submit-time">{{ indiv_work.submission_time|date:"c" }}</span>
              </div>
            </div>
            
            <div class="num-attachments"><span class="num">{{ indiv_work.num_attachments }}</span>Attachment{{ indiv_work.num_attachments|pluralize }}</div>
            <div class="user">
              <div class="dp" style="background-image: url('{{ indiv_work.submission_by.account.avatar_url }}')">
              </div>
              <div class="name">{{indiv_work.submission_by.account.user_full_name}}</div>
            </div>
          </div>
        </a>
        {% endfor %}
        {% for unsub_group in unsubmitting_groups %}
        <div class="unsubmitting">
          <div class="info">
            <i class='bx bx-calendar-exclamation'></i>
            <span>Assigned, not Submitted</span>
          </div>
          <div class="group-members">
            <div class="title">Group Members</div>
            <ul>
              {% for member in unsub_group.members.all %}
              <li>
                <div class="dp" style="background-image: url('{{ member.account.avatar_url }}')">
                </div>
                <div class="name">{{member.account.user_full_name}}</div>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
        {% endfor %}
        {% for unsub_indiv in unsubmitting_indiv  %}
        <div class="unsubmitting">
          <div class="info">
            <i class='bx bx-calendar-exclamation'></i>
            <span>Assigned, not Submitted</span>
          </div>
          <div class="user">
            <div class="dp" style="background-image: url('{{ unsub_indiv.account.avatar_url }}')">
            </div>
            <div class="name">{{unsub_indiv.account.user_full_name}}</div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% else %}
    <div class="fileupload-info-con p-3 shadow-lg rounded bg-white" style="display: none;" id="fileupload-info-con">
      <div class="content" id="ongoing-upload-status">
        <div class="title text-center mb-1">Uploading File</div>
        <div id="fileuploadprogress" class="progress" role="progressbar" aria-label="Animated striped example" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
          <div id="fileuploadprogress_bar" class="progress-bar progress-bar-striped progress-bar-animated" style="width: 0%"></div>
        </div>
        <div id="fileupload_percentage" class="percentage text-center">0%</div>
      </div>
      <div class="error-info" style="display: none;" id="fileuploaderror-info">
        <i class='bx bx-info-circle'></i>
        <div class="error-text">File upload failed</div>
      </div>
    </div>
    <div class="my-work bg-white">
      <div class="title">My Work</div>
      <div class="info">
        <div class="due-date">
          <span class="time" id="{{task.id}}-due-time">{{ task.deadline|date:'c' }}</span>
        </div>
      </div>
      {% if work %}
      <div class="uploaded-work">
        <ul>
          {% for file in work.attachments %}
          <li>
            <a href="{% url 'classroom:tasks:view_work_file' file.work.task.classroom.id file.id %}" target="blank" class="attachment-item">
              <i class='{{ file.css_class }}'></i>
              <div class="filename">{{ file.filename|truncatechars:25 }}</div>
            </a>
          </li>
          {% endfor %}
        </ul>
        {% if group %}<div class="submitted-by">{{ work.submission_by.account.user_full_name }}</div>{% endif %}
        {% if work.score %}
        <div class="obtained-score"><i class='bx bx-trophy'></i><span class="point">{{work.score}}</span>Points</div>
        {% if work.remarks %}
        <div class="remarks-con">
          <div class="title">
            <i class='bx bx-list-check'></i>
            <span>Remarks</span>
          </div>
          <div class="content py-2">{{work.remarks}}</div>
        </div>
        {% endif %}
        {% else %}
        {% if work.is_submitted %}
        <div class="buttons-container">
          <button class="action-btn unsubmit" id="alt_sub_status_btn">Unsubmit</button>
          <button class="del-btn" id="work-del-btn" style="display: none;"><i class='bx bx-trash-alt'></i></button>
        </div>
        {% else %}
        <div class="buttons-container">
          <button class="action-btn submit" id="alt_sub_status_btn">Submit</button>
          <button class="del-btn" id="work-del-btn"><i class='bx bx-trash-alt'></i></button>
        </div>
        {% endif %}
        
        {% endif %}
      </div>
      {% else %}
      <div class="form">
        <div class="attachement-container">
          <input type="file" id="post-files" name="post-file" multiple="multiple">
          <label for="post-files"><i class='bx bx-upload'></i>Upload Work</label>
          <div class="status-text" id="postfiles-file-status" style="display: none;">files uploading</div>
        </div>
      </div>
      {% endif %}
      {% if group %}
      <div class="teammates">
        <div class="title">Group Members</div>
        <ul>
          {% for member in group.members.all %}
          <li>
            <div class="dp" style="background-image: url('{{ member.account.avatar_url }}')">
            </div>
            <div class="name">{{member.account.user_full_name}}</div>
          </li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}
    </div>
    {% endif %}
  </div>
</div>
{% endblock content %}

{% block script %}
<script type="text/javascript" src="{% static 'tasks/scripts/task.js' %}"></script>
<script type="text/javascript" src="{% static 'classroom/scripts/localtimes.js' %}"></script>
{% if not is_teacher %}
<script>
  const upload_work_url = "{% url 'classroom:tasks:upload_work' task.classroom.id task.id %}"
  {% if work %}
  const change_work_submission_status_api = "{% url 'classroom:tasks:change_work_submission_status' work.task.classroom.id work.id %}"
  const delete_work_api_url = "{% url 'classroom:tasks:delete_work' work.task.classroom.id work.id %}"
  {% endif %}
  let csrftoken = "{{ csrf_token }}"
</script>
{% endif %}
{% endblock script %}