accounts/urls.py
from django.urls import path
from .views import (LoginView, SignupView, LogoutView, 
                    api_login, api_signup, set_avatar, view_profile, send_verification_email_api, 
                    edit_profile, update_profile, update_password_get, update_password_api, verify_user,
                    send_recovery_email_api, reset_password_get, forgot_password_get, reset_password_api)

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name="user_login_get"),
    path('api/login', api_login, name="user_login_post"),
    path('logout/', LogoutView.as_view(), name="user_logout"),
    path('signup/', SignupView.as_view(), name="user_signup_get"),
    path('api/verify/sendmail', send_verification_email_api, name="send_verification_email_api"),
    path('verify/<uidb64>/<token>', verify_user, name="verify_user"),
    path('recovery', forgot_password_get, name="forgot_password_get"),
    path('api/recovery/sendmail', send_recovery_email_api, name="send_recovery_email_api"),
    path('recovery/<uidb64>/<token>', reset_password_get, name="reset_password_get"),
    path('api/recovery/setpassword/<uidb64>/<emailb64>', reset_password_api, name="reset_password_api"),
    path('profile/<int:pk>', view_profile, name="view_profile"),
    path('profile/update', update_profile, name="update_profile_api"),
    path('profile/update/password', update_password_get, name="update_password_get"),
    path('profile/api/update/password', update_password_api, name="update_password_api"),
    path('profile/edit', edit_profile, name="edit_profile"),
    path('api/signup', api_signup, name="user_signup_post"),
    path('profile/avatar/set', set_avatar, name="set_avatar"),
]
   

classroom/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('newclassroom', views.create_classroom, name="create_classroom_api"),
    path('join', views.classroom_join_api, name="classroom_join_api"),
    path('<str:pk>/changecode', views.change_join_code, name="change_join_code"),
    path('<str:pk>/posts', views.ClassroomPostsView.as_view(), name="classroom_posts"),
    path('<str:pk>/update', views.UpdateClassroomAV.as_view(), name="update_classroom"),
    path('<str:pk>/delete', views.delete_classroom_api, name="delete_classroom_api"),
    path('<str:pk>/mycongrats', views.get_congrats_api, name="get_congrats_api"),
    path('<str:pk>/congratulate', views.congratulate_user, name="congratulate_user"),
    path('<str:pk>/update/banner', views.set_banner, name="set_banner"),
    path('<str:pk>/update/banner/todefault', views.set_banner_to_default, name="set_banner_to_default"),
    path('<str:pk>/addteacher', views.add_teacher, name="add_teacher"),
    path('<str:cls_pk>/assessments/update', views.update_assessments, name="update_assessments"),
    path('<str:cls_pk>/assessments/delete', views.delete_assessment_meta, name="delete_assessment_meta"),
    path('<str:cls_pk>/performance', views.classroom_performance_api, name="classroom_performance_api"),
    path('<str:cls_pk>/rankings', views.rankings, name="get_ranking_api"),
    path('<str:cls_pk>/assessmentslist', views.AssessmentsList.as_view(), name="get_assessments_api"),
    # path('<str:pk>/edit', views.update_classroom_info, name="update_classroom"),
    path('<str:pk>/removeuser', views.remove_user_from_classroom, name="remove_user_from_classroom"),
    path('post/<str:pk>/postcomment', views.post_comment, name="post_comment"),
    path('post/<str:pk>/update', views.update_post_des_and_rm_files, name="update_post_des_and_rm_files"),
    path('post/<str:pk>/delete', views.delete_post, name="delete_post_api"),
]
   

classroom/urls.py
from django.urls import path, include
from .views import *
app_name = 'classroom'

urlpatterns = [
    path('', starter_homepage, name='starter'),
    path('classes', ClassesDashboard.as_view(), name="homepage"), # it's actually classes homepage, requires authentication
    path('classroom/new', create_classroom, name="create_classroom"),
    path('classroom/api/', include("classroom.api.urls")),
    path('classroom/<str:pk>', ClassroomDetail.as_view(), name="classroom_detail"),
    path('classroom/<str:pk>/connections', ClassroomConnections.as_view(), name="classroom_connections"),
    path('classroom/<str:pk>/rankings', ClassroomRanking.as_view(), name="classroom_ranking"),
    path('classroom/<str:pk>/assessment/create', create_assessment, name="create_assessment"),
    path('classroom/<str:pk>/assessment', view_assessment, name="view_assessment"),
    path('classroom/<str:cls_pk>/assessment/<int:pk>', view_student_assessment, name="view_student_assessment"),
    path('classroom/<str:pk>/assessment/printf', view_assessment_printf, name="view_assessment_printf"),
    path('classroom/<str:cls_pk>/assessments/download/excel', download_assessment_excel, name="download_assessment_excel"),
    path('classroom/<str:pk>/about', ClassroomAbout.as_view(), name="classroom_about"),
    path('classroom/<str:pk>/assignment/new', create_assignment, name="create_assignment"),
    path('classroom/<str:pk>/edit', edit_classroom, name="edit_classroom"),
    path('classroom/join/<str:cls_code>', join_classroom, name="join_classroom"),
    # topics
    path('classroom/<str:pk>/topics/<str:topic_id>', topic_posts, name="topic_posts"),
    # posts
    path('classroom/<str:pk>/post', create_post, name="post_to_classroom"),
    path('classroom/post/<str:pk>', PostDetail.as_view(), name="post_detail"),
    path('classroom/post/<str:pk>/edit', edit_post, name="edit_post"),
    path('classroom/post/<str:pk>/newfile', uploadPostFile, name="uploadPostFile"),
    path('classroom/post/<str:pk>/delete', delete_post, name="delete_post"),
    # assignment
    path('classroom/<str:pk>/assignments', classroom_assignment, name="view_classroom_assignment"),
    path('classroom/assignment/<str:pk>', view_assignment, name="view_assignment"),
    # students
    path('classroom/<str:pk>/students', classroom_students, name="classroom_students"),
    path('classroom/<str:pk>/groups', classroom_groups, name="classroom_groups"),
    # files
    path('classroom/<str:pk>/files', classroom_files, name="classroom_files"),
    # tasks
    path('classroom/<str:cls_pk>/task/', include("tasks.urls")),
]
   

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('classroom.urls')),
    # weeklies
    path('weeklies/', include('weeklies.urls')),
    path('weeklies/test/', include('weekly_test.urls')),
    path('weeklies/test/api/', include('weekly_test.api.urls')),
    # auth
    path('account/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from tasks import views
app_name = 'tasks'

# <included from classroomn.urls> url: classroom/<str:cls_pk>/task/

urlpatterns = [
    path('new', views.create_task, name="create_task"),
    path('<str:pk>', views.TaskDetail.as_view(), name="view_task"),
    path('<str:pk>/delete', views.delete_task_get, name="delete_task_get"),
    path('<str:pk>/api/delete', views.delete_task, name="delete_task_api"),
    path('files/<int:pk>', views.view_task_file, name="view_task_file"),
    path('work/<str:pk>', views.WorkDetail.as_view(), name="view_work"),
    path('<str:pk>/upload_work', views.upload_work, name="upload_work"),
    path('work/files/<int:pk>', views.view_work_file, name="view_work_file"),
    path('work/<str:pk>/changesubmission', views.change_work_submission_status, name="change_work_submission_status"),
    path('work/<str:pk>/delete', views.delete_work, name="delete_work"),
    path('work/<str:pk>/marking', views.update_work_score, name="update_work_score"),
    path('work/<str:pk>/remarks', views.update_work_remarks, name="update_work_remarks"),
]
   

classroom/views.py
from excel_response import ExcelResponse
from dateutil import parser
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, JsonResponse, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.templatetags.static import static
from django.views.generic import TemplateView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from .utilities import get_float_or_none, prepare_excel_file_data
from .models import (Classroom, ClassroomPost, PostTopic, PostAttachment,
                     Comment, Assignment, AssignmentAttachment, AssessmentMeta, Assessment)



def render_underDev(request):
    return render(request,"classroom/under_dev.html")

def render_info_or_error(request, heading, description, css_class="info"):
    context = {}
    context['heading'] = heading
    context['description'] = description
    context['css_class'] = css_class
    return render(request, 'classroom/infoerror.html', context=context)


def starter_homepage(request):
    if request.user.is_authenticated:
        if hasattr(request.user, 'account'):
            return redirect('classroom:homepage')
        else:
            return render_info_or_error(request, "No Classroom Account", "This is an admin account. Please create a general account to access this section")
    else:
        return render(request, "classroom/homepage.html")


class ClassesDashboard(LoginRequiredMixin, TemplateView):
    template_name = 'classroom/classes_home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        my_teachings = Classroom.objects.filter(teachers=self.request.user).order_by('created')
        my_learnings = Classroom.objects.filter(students=self.request.user, active=True).order_by('created')
        classrooms = {}
        if len(my_teachings) > 0:
            classrooms['my_teachings'] = my_teachings
        if len(my_learnings) > 0:
            classrooms['my_learnings'] = my_learnings
        if len(classrooms) > 0:
            context['classrooms'] = classrooms
        return context


class ClassroomDetail(LoginRequiredMixin, DetailView):
    template_name = 'classroom/classroom_detail.html'
    model = Classroom
    
    def get_object(self):
        classroom = super().get_object()
        if self.request.user in classroom.teachers.all():
            return classroom
        else:
            if (self.request.user not in classroom.students.all()) or (not classroom.active):
                raise Http404
            else:
                return classroom
            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        classroom = self.get_object()
        join_link = self.request.build_absolute_uri(reverse("classroom:join_classroom", args=(classroom.join_code,)))
        invitation_text = f"""Join {classroom.name} by using this code: {classroom.join_code}\nor by using this url: {join_link}"""
        context["invitation_text"] = invitation_text
        if self.request.user in classroom.teachers.all():
            query_set = classroom.ongoing_tests
            if query_set.count() > 0:
                context['teacher_tests'] = query_set
        elif self.request.user in classroom.students.all():
            query_set = classroom.students_non_participating_ongoing_tests(student=self.request.user)
            unsubmitted_tests = self.request.user.account.classroom_unsubmitted_tests(classroom)
            if (query_set.count() + unsubmitted_tests.count()) > 0:
                context['has_student_tests'] = True
                if query_set.count() > 0:
                    context['student_tests'] = query_set
                if unsubmitted_tests.count() > 0:
                    context['unsubmitted_tests'] = unsubmitted_tests
        return context


class ClassroomRanking(LoginRequiredMixin, DetailView):
    template_name = 'classroom/ranking.html'
    model = Classroom
    def get_object(self):
        classroom = super().get_object()
        if self.request.user in classroom.teachers.all():
            return classroom
        else:
            if (self.request.user not in classroom.students.all()) or (not classroom.active):
                raise Http404
            else:
                return classroom
                
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        static_images = {}
        static_images['leaderboard'] = static('classroom/images/ranking/leaderboard.svg')
        static_images['blank_dp'] = static('accounts/images/blank-dp.svg')
        static_images['blank_champion'] = static('classroom/images/ranking/trophy.png')
        static_images['blank_medal'] = static('classroom/images/ranking/medals.png')
        static_images['first_rank'] = static('classroom/images/ranking/first_rank.png')
        static_images['second_rank'] = static('classroom/images/ranking/second-rank.png')
        static_images['third_rank'] = static('classroom/images/ranking/third-rank.png')
        context['static_images'] = static_images
        return context
        
        


class ClassroomConnections(LoginRequiredMixin, DetailView):
    template_name = 'classroom/view_peoples.html'
    model = Classroom
    def get_object(self):
        classroom = super().get_object()
        if (self.request.user in classroom.teachers.all()) or (self.request.user in classroom.students.all()):
            return classroom
        else:
            raise Http404
        

class ClassroomAbout(LoginRequiredMixin, DetailView):
    template_name = 'classroom/classroom_about.html'
    model = Classroom
    def get_object(self):
        classroom = super().get_object()
        if (self.request.user in classroom.teachers.all()) or (self.request.user in classroom.students.all()):
            return classroom
        else:
            raise Http404
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        classroom = context['classroom']
        context["join_link"] = self.request.build_absolute_uri(reverse("classroom:join_classroom", args=(classroom.join_code,)))
        return context
        
        
        

class PostDetail(LoginRequiredMixin, DetailView):
    template_name = 'classroom/post_detail.html'
    model = ClassroomPost
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        classroom_post = self.get_object()
        threads = Comment.objects.filter(post=classroom_post, parent=None).order_by('comment_time')
        context['threads'] = threads
        return context


@login_required
def create_assessment(request, pk):
    if request.method == "POST":
        classroom = get_object_or_404(Classroom, pk=pk)
        if request.user in classroom.teachers.all():
            assessmentmeta_data = {}
            assessmentmeta_data['classroom'] = classroom
            assessmentmeta_data['attendance_marks'] = get_float_or_none(request.POST.get("attendance"))
            assessmentmeta_data['classtest_marks'] = get_float_or_none(request.POST.get("classtest"))
            assessmentmeta_data['pre_class_marks'] = get_float_or_none(request.POST.get("pre-cls-marks"))
            assessmentmeta_data['in_class_marks'] = get_float_or_none(request.POST.get("in-cls-marks"))
            assessmentmeta_data['post_class_marks'] = get_float_or_none(request.POST.get("post-cls-marks"))
            if all([data!=None for data in assessmentmeta_data.values()]):
                meta = AssessmentMeta.objects.create(**assessmentmeta_data)
                for student in classroom.students.all():
                    Assessment.objects.create(meta=meta, student=student)
                return redirect('classroom:view_assessment', pk=classroom.id)
            else:
                return render_info_or_error(request, "ERROR 400", "Bad Request", 'error')
        else:
            return render_info_or_error(request, "ERROR 403", "Access Denied", 'error')


@login_required
def view_assessment(request, pk):
    classroom = get_object_or_404(Classroom, pk=pk)
    context = {}
    context['classroom'] = classroom
    
    if request.user in classroom.teachers.all():
        if hasattr(classroom, "assessmentmeta"):
            context['meta'] = classroom.assessmentmeta
            context['check_svg'] = static('classroom/images/checked-tick.svg')
        return render(request, 'classroom/assessment_list.html', context=context)
    elif request.user in classroom.students.all():
        assessment_qs = Assessment.objects.filter(student=request.user, meta__classroom=classroom)
        if len(assessment_qs) > 0:
            context['assessment'] = assessment_qs[0]
        return render(request, 'classroom/assessment_student.html', context=context)
    else:
        return render_info_or_error(request, "ERROR 403", "Access Denied", 'error')


@login_required
def view_student_assessment(request, cls_pk, pk):
    classroom = get_object_or_404(Classroom, pk=cls_pk)
    context = {}
    context['classroom'] = classroom
    if request.user in classroom.teachers.all():
        assessment = get_object_or_404(Assessment, pk=pk, meta__classroom=classroom)
        context['assessment'] = assessment
        return render(request, 'classroom/assessment_student.html', context=context)
    

@login_required
def download_assessment_excel(request, cls_pk):
    classroom = get_object_or_404(Classroom, pk=cls_pk)
    if request.user in classroom.teachers.all():
        if hasattr(classroom, 'assessmentmeta'):
            meta = classroom.assessmentmeta
            data = prepare_excel_file_data(meta)

classroom/templates/classroom/assessment_list.html
{% extends 'classroom/base.html' %}
{% block style %} {% load static %} {% load my_tags %}
<link rel="stylesheet" href="{% static 'classroom/styles/assessment.css' %}">
<link rel="stylesheet" href="{% static 'classroom/styles/navbar.css' %}">
<link rel="stylesheet" href="{% static 'classroom/styles/loaders.css' %}">
<link rel="stylesheet" href="{% static 'classroom/styles/commons.css' %}">
{% endblock style %}
{% block title %}<title>{{classroom.name}} Assessment</title>{% endblock title %}
{% block nav %}
<ul class="navbar-nav mb-2 mb-lg-0">
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="{% url 'classroom:classroom_detail' classroom.id %}">Dashboard</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_connections' classroom.id %}">Participants</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_ranking' classroom.id %}">Ranking</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Assessment</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_about' classroom.id %}">About</a>
  </li>
</ul>
{% endblock nav %}

{% block content %}

{% if meta %}
<!-- loader -->
<div class="loader-container mt-5" id="loader-con" >
  <div class="loader d-flex justify-content-center">
    <div class="lds-facebook"><div></div><div></div><div></div></div>
  </div>
  <div class="infotext text-center">Loading Data</div>
</div>
<div class="alert-component" id="alert-component-con" style="display: none;">
  <div class="alert-inner">
    <ul id="notification-alert-list">
      {% comment %} <li>
        <div class="alert-con info shadow">
          <img src="./img/confetti.svg" alt="">
          <div class="alert-info ms-2">You've congratulated user for his first position</div>
        </div>
      </li>
      <li>
        <div class="alert-con dark shadow">
          <img src="./img/alert.svg" alt="">
          <div class="alert-info ms-2">You've already congratulated user for his rank in this week</div>
        </div>
      </li>
      <li>
        <div class="alert-con shadow with-dp">
          <img src="./img/user1.jpg" class="shadow dp">
          <div class="alert-info ms-2">User has congratulated you on your ranking</div>
        </div>
      </li> {% endcomment %}
    </ul>
  </div>
</div>
<!-- list -->
<div class="assessment-list container my-4" id="assessment-list-con" style="display: none;">
  <div class="heading mb-3">
    <i class='bx bx-stats'></i>
    <span class="title">{{classroom.name}} Assessment Table</span>
  </div>
  <div class="assessment-table bg-white p-3 shadow">
      <table>
          <thead>
              <tr>
                  <th>Name</th>
                  <th>Registration No</th>
                  <th>Attendance ({{meta.get_attendance_marks}})</th>
                  <th>Class Test ({{meta.get_classtest_marks}})</th>
                  <th>Pre Class ({{meta.get_preclass_marks}})</th>
                  <th>In Class ({{meta.get_inclass_marks}})</th>
                  <th>Post Class ({{meta.get_postclass_marks}})</th>
                  <th>Total ({{meta.total_marks}})</th>
              </tr>
          </thead>
          <tbody id="assessments-tbody">
          </tbody>
      </table>
      <div class="submit mt-3">
        <button class="btn-1 shadow-sm" id="a-save-btn">Save</button>
      </div>
  </div>
  <div class="info mt-4">
    <div class="student-stats"><span class="num">{{meta.assessments.count}}</span> of the <span class="num">{{meta.classroom.students.count}}</span> students has been assessed</div>
    <div class="btn-container">
      <a href="{% url 'classroom:download_assessment_excel' classroom.id %}" class="download btn-a shadow-sm" download=""><i class='bx bx-table'></i><span>Download as Excel</span></a>
      <button class="edit-btn shadow-sm ms-2" id="rst-assessment-btn"><i class='bx bx-refresh'></i><span>Reset All</span></button>
    </div>
  </div>
  <a href="{% url 'classroom:view_assessment_printf' meta.classroom.id %}" class="print btn-a shadow ms-2" target="blank"><i class='bx bx-printer'></i><span>Print Format</span></a>
</div>
{% else %}
<div class="create-assessment container mt-4">
  <div class="title mb-4"><i class='bx bx-code me-1'></i><span>Define total marks</span></div>
  <form action="{% url 'classroom:create_assessment' classroom.id %}" method="POST"> {% csrf_token %}
    <div class="input-container">
        <div class="inset-float-textinput-fluid attendance-field mb-2">
            <input class="inp_input" type="text" name="attendance" id="attendance" placeholder=" " required="">
            <label class="inp_label" for="attendance">Attendance</label>
        </div>
        <div class="inset-float-textinput-fluid title-field mb-2">
            <input class="inp_input" type="text" name="classtest" id="classtest" placeholder=" " required="">
            <label class="inp_label" for="classtest">Class Test</label>
        </div>
        <div class="auto-fields p-3 rounded">
            <div class="fields-title mb-2"><i class='bx bx-refresh me-1'></i><span>Score to be generated from weekly activities</span></div>
            <div class="inset-float-textinput-fluid mb-2">
                <input class="inp_input" type="text" name="pre-cls-marks" id="pre-cls-marks" placeholder=" " required="">
                <label class="inp_label" for="pre-cls-marks">Weekly PreClass marks</label>
            </div>
            <div class="inset-float-textinput-fluid mb-2">
                <input class="inp_input" type="text" name="in-cls-marks" id="in-cls-marks" placeholder=" " required="">
                <label class="inp_label" for="in-cls-marks">Weekly InClass marks</label>
            </div>
            <div class="inset-float-textinput-fluid">
                <input class="inp_input" type="text" name="post-cls-marks" id="post-cls-marks" placeholder=" " required="">
                <label class="inp_label" for="post-cls-marks">Weekly PostClass marks</label>
            </div>
        </div>
        <div class="submit-con mt-3">
            <button type="submit" class="btn-1 shadow-sm">Create Assessments</button>
        </div>
    </div>
  </form>
</div>
{% endif %}
{% endblock content %}

{% block script %}
<script>
  const assessments_url = "{% url 'classroom:get_assessments_api' classroom.id %}";
  const update_assessment_url = "{% url 'classroom:update_assessments' classroom.id %}";
  const delete_assessment_url = "{% url 'classroom:delete_assessment_meta' classroom.id %}";
  const csrftoken = "{{csrf_token}}";
  const check_svg = "{{check_svg}}";
</script>
<script src="{% static 'classroom/scripts/assessment.js' %}"></script>
{% endblock script %}

classroom/templates/classroom/infoerror.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    {% load static %}
    <link rel="stylesheet" href="{% static 'classroom/styles/under_dev.css' %}">
    <title>Flipped Classroom</title>
</head>
<body>
    <div class="main">
        <div class="content {{css_class}}">
            <div class="heading">{{heading}}</div>
            <div class="description">{{description}}</div>
            <a href="{% url 'classroom:starter' %}"><i class='bx bx-home-alt-2'></i></a>
        </div>
    </div>
</body>
</html>

classroom/templates/classroom/topicdetail.html
{% extends 'classroom/base.html' %}
{% block style %} {% load static %}
<link rel="stylesheet" href="{% static 'classroom/styles/topicdetail.css' %}">
<link rel="stylesheet" href="{% static 'classroom/styles/navbar.css' %}">
{% endblock style %}
{% block title %}<title>{{ topic.name }}</title>{% endblock title %}
{% block nav %}
<ul class="navbar-nav mb-2 mb-lg-0">
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="{% url 'classroom:classroom_detail' topic.classroom.id %}">Dashboard</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_connections' topic.classroom.id %}">Participants</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_ranking' topic.classroom.id %}">Ranking</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:view_assessment' topic.classroom.id %}">Assessment</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_about' topic.classroom.id %}">About</a>
  </li>
</ul>
{% endblock nav %}

{% block content %}
<div class="topic-name">
    <i class='bx bxs-tag-alt'></i>
    <span class="name">{{ topic.name }}</span>
</div>
<div class="posts">
    <div class="heading"><i class='bx bx-file'></i><span>Posts</span></div>
    <div class="posts-container">
        {% for post in topic.posts %}
        <div class="post-item">
            <div class="contents">
                <a href="{% url 'classroom:post_detail' post.id %}" class="title">{{ post.description }}</a>
                <div class="post-time time" id="post-{{post.id}}-time">{{ post.posted|date:"c" }}</div>
                {% if post.has_topics %}
                <div class="topics">
                    {% for post_topic in post.topics.all %}
                    <a href="{% url 'classroom:topic_posts' post_topic.classroom.id post_topic.str_id %}" class="topic"><span class="content"><i class='bx bx-tag-alt'></i><span>{{ post_topic.name }}</span></span></a>
                    {% endfor %}
                </div>
                {% endif %}
                <div class="info">
                    <div class="info-item"><i class='bx bx-paperclip'></i><span>{{ post.num_attachments }} attachments</span></div>
                    <div class="info-item"><i class='bx bx-comment'></i><span>{{ post.num_comments }} comments</span></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'classroom/scripts/localtimes.js' %}"></script>
{% endblock script %}