classroom/urls.py
from django.urls import path, include
from .views import *
app_name = 'classroom'

urlpatterns = [
    path('', starter_homepage, name='starter'),
    path('classes', ClassesDashboard.as_view(), name="homepage"), # it's actually classes homepage, requires authentication
    path('classroom/new', create_classroom, name="create_classroom"),
    path('classroom/api/', include("classroom.api.urls")),
    path('classroom/<str:pk>', ClassroomDetail.as_view(), name="classroom_detail"),
    path('classroom/<str:pk>/connections', ClassroomConnections.as_view(), name="classroom_connections"),
    path('classroom/<str:pk>/rankings', ClassroomRanking.as_view(), name="classroom_ranking"),
    path('classroom/<str:pk>/assessment/create', create_assessment, name="create_assessment"),
    path('classroom/<str:pk>/assessment', view_assessment, name="view_assessment"),
    path('classroom/<str:cls_pk>/assessment/<int:pk>', view_student_assessment, name="view_student_assessment"),
    path('classroom/<str:pk>/assessment/printf', view_assessment_printf, name="view_assessment_printf"),
    path('classroom/<str:cls_pk>/assessments/download/excel', download_assessment_excel, name="download_assessment_excel"),
    path('classroom/<str:pk>/about', ClassroomAbout.as_view(), name="classroom_about"),
    path('classroom/<str:pk>/assignment/new', create_assignment, name="create_assignment"),
    path('classroom/<str:pk>/edit', edit_classroom, name="edit_classroom"),
    path('classroom/join/<str:cls_code>', join_classroom, name="join_classroom"),
    # topics
    path('classroom/<str:pk>/topics/<str:topic_id>', topic_posts, name="topic_posts"),
    # posts
    path('classroom/<str:pk>/post', create_post, name="post_to_classroom"),
    path('classroom/post/<str:pk>', PostDetail.as_view(), name="post_detail"),
    path('classroom/post/<str:pk>/edit', edit_post, name="edit_post"),
    path('classroom/post/<str:pk>/newfile', uploadPostFile, name="uploadPostFile"),
    path('classroom/post/<str:pk>/delete', delete_post, name="delete_post"),
    # assignment
    path('classroom/<str:pk>/assignments', classroom_assignment, name="view_classroom_assignment"),
    path('classroom/assignment/<str:pk>', view_assignment, name="view_assignment"),
    # students
    path('classroom/<str:pk>/students', classroom_students, name="classroom_students"),
    path('classroom/<str:pk>/groups', classroom_groups, name="classroom_groups"),
    # files
    path('classroom/<str:pk>/files', classroom_files, name="classroom_files"),
    # tasks
    path('classroom/<str:cls_pk>/task/', include("tasks.urls")),
]
   

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('classroom.urls')),
    # weeklies
    path('weeklies/', include('weeklies.urls')),
    path('weeklies/test/', include('weekly_test.urls')),
    path('weeklies/test/api/', include('weekly_test.api.urls')),
    # auth
    path('account/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from tasks import views
app_name = 'tasks'

# <included from classroomn.urls> url: classroom/<str:cls_pk>/task/

urlpatterns = [
    path('new', views.create_task, name="create_task"),
    path('<str:pk>', views.TaskDetail.as_view(), name="view_task"),
    path('<str:pk>/delete', views.delete_task_get, name="delete_task_get"),
    path('<str:pk>/api/delete', views.delete_task, name="delete_task_api"),
    path('files/<int:pk>', views.view_task_file, name="view_task_file"),
    path('work/<str:pk>', views.WorkDetail.as_view(), name="view_work"),
    path('<str:pk>/upload_work', views.upload_work, name="upload_work"),
    path('work/files/<int:pk>', views.view_work_file, name="view_work_file"),
    path('work/<str:pk>/changesubmission', views.change_work_submission_status, name="change_work_submission_status"),
    path('work/<str:pk>/delete', views.delete_work, name="delete_work"),
    path('work/<str:pk>/marking', views.update_work_score, name="update_work_score"),
    path('work/<str:pk>/remarks', views.update_work_remarks, name="update_work_remarks"),
]
   

weeklies/urls.py
from django.urls import path, include
from .views import weeklyDetail, addFiles, downloadFile, edit_post, edit_weekly_view, delete_weekly_view

app_name = "weeklies"

# 'weeklies/' --->

urlpatterns = [
    path('<str:cls_pk>/api/', include('weeklies.api.urls')),
    path('<str:cls_pk>/week/<int:weeknum>', view=weeklyDetail, name='weeklydetail'),
    path('week/<str:pk>/edit', view=edit_weekly_view, name='edit_weekly'),
    path('week/<str:pk>/delete', view=delete_weekly_view, name='delete_weekly'),
    path('<str:weekly_pk>/file/upload', view=addFiles, name='uploadweeklyfiles'),
    path('<str:weekly_pk>/post/<int:pk>/edit', view=edit_post, name='edit_post'),
    path('<str:weekly_pk>/file/<int:pk>/download', view=downloadFile, name='downloadweeklyfile')
]

weekly_test/api/urls.py
from django.urls import path, include
from . import views


# test/api/weeklies
app_name = "weekly_test_api"

urlpatterns = [
    path('<str:pk>/create/', views.create_test, name='create_test'),
    path('<str:pk>/delete/', views.delete_test, name='delete_test'),
    path('issue/', views.issue_answer_sheet, name='issue_answer_sheet'),
    path('livestats/<cls_pk>', views.live_test_stats, name='live_test_stats'),
    path('<str:pk>/answersheets', views.TestAnswersheetsView.as_view(), name='test_answersheets'),
    path('answersheet/<str:answersheet_pk>/updatescore', views.update_score, name='update_score')
]

weekly_test/urls.py
from django.urls import path, include
from weekly_test import views


# test/weeklies
app_name = "weekly_test"

urlpatterns = [
    path('<str:pk>/start', views.take_test, name='take_test'),
    path('<str:pk>/new', views.QuestionCreate.as_view(), name='create_question'),
    path('<str:pk>/questions', views.view_ques, name='view_ques'),
    path('<str:pk>/view', views.view_test, name='view_test'),
    path('<str:pk>/delete', views.delete_test_get, name='delete_test_get'),
    path('answersheet/<str:pk>', views.view_answersheet, name='view_answersheet'),
]

weekly_test/api/views.py
from dateutil import parser
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework import status
from django.utils import timezone
from django.shortcuts import get_object_or_404
from datetime import timedelta
from weekly_test.models import WeeklyTest, AnswerSheet, DescriptiveAnswer
from weekly_test.utils import send_newTestEmailNotif
from .serializer import TestSerializer, QuestionSerializer, OptionSerializer, AnswerSheetSerializer
from .paginations import AnswerSheetPagination
from rest_framework.permissions import IsAuthenticated
from .permission import IsUserTeacherOfClassroom
from rest_framework.generics import ListAPIView
from weeklies.models import Weekly
from classroom.models import Classroom

@api_view(["POST"])
def create_test(request, pk):
    if request.method == "POST":
        weekly = get_object_or_404(Weekly, pk=pk)
        testserializer = TestSerializer(data=request.data.get('test'))
        cc = request.GET.get("contentcode", False)
        if cc != False:
            if cc == '0':
                testserializer.initial_data['preclass'] = True
            elif cc == '1':
                testserializer.initial_data['inclass'] = True
            elif cc == '2':
                testserializer.initial_data['postclass'] = True
            else:
                return Response(status=status.HTTP_400_BAD_REQUEST, data={'error':'invalid contentcode'})
        schedule = parser.parse(testserializer.initial_data['schedule'])
        expiration = parser.parse(testserializer.initial_data['expiration'])
        testserializer.initial_data['weekly'] = weekly.id
        testserializer.initial_data['schedule'] = schedule
        testserializer.initial_data['expiration'] = expiration
        
        user = request.user
        if testserializer.is_valid():
            test = testserializer.save(user=user)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST, data=testserializer.errors)
        for question in request.data.get('questions'):
            question_data = question['meta']
            question_data['test'] = test.id
            questionserializer = QuestionSerializer(data=question_data)
            if questionserializer.is_valid():
                question_obj = questionserializer.save()
            else:
               return Response(status=status.HTTP_400_BAD_REQUEST, data={'error':questionserializer.errors})
            if not question_data['is_descriptive']:
                for option in question['options']:
                    del option['id']
                    option['question'] = question_obj.id
                    option_serializer = OptionSerializer(data=option)
                    if option_serializer.is_valid():
                        option_serializer.save()
                    else:
                       return Response(status=status.HTTP_400_BAD_REQUEST, data={'error':option_serializer.errors})
        try:
            send_newTestEmailNotif(test, request)
        except Exception as e:
            print(e)
        return Response(data=testserializer.data,status=status.HTTP_201_CREATED)


@api_view(['POST'])
def issue_answer_sheet(request):
    if request.method == "POST":
        answer_sheet_pk = request.data.get("answer_sheet_pk")
        try:
            ans_sheet = AnswerSheet.objects.get(pk=answer_sheet_pk)
        except AnswerSheet.DoesNotExist:
            return Response(data={'info': 'answersheet not found'}, status=status.HTTP_404_NOT_FOUND)
        duration_seconds = ans_sheet.test.duration_seconds
        starttime = ans_sheet.issue_time
        if starttime is None:
            starttime = timezone.now()
            ans_sheet.issue_time = starttime
            ans_sheet.save()
        endtime = starttime + timedelta(seconds=duration_seconds)
        return Response(data={'pk': answer_sheet_pk, 'duration':duration_seconds, 'endtime':endtime})


@api_view(["DELETE"])
@permission_classes([IsAuthenticated])
def delete_test(request, pk):
    test = get_object_or_404(WeeklyTest, pk=pk)
    if request.user in test.weekly.classroom.teachers.all():
        test.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    else:
        return Response(status=status.HTTP_403_FORBIDDEN)



@api_view(["POST"])
@permission_classes([IsAuthenticated])
def live_test_stats(request, cls_pk):
    try:
        classroom = Classroom.objects.get(pk=cls_pk)
    except Classroom.DoesNotExist:
        return Response(data={'info':'classroom not found'}, status=status.HTTP_404_NOT_FOUND)
    if request.user not in classroom.teachers.all():
        return Response(data={'info':'access denied'}, status=status.HTTP_403_FORBIDDEN)
    live_tests = []
    try:
        test_pks = request.data['test_pks']
    except Exception as e:
        return Response(data={'info':'bad request'}, status=status.HTTP_400_BAD_REQUEST)
    for test_pk in test_pks:
        try:
            test = WeeklyTest.objects.get(pk=test_pk)
            live_tests.append(test)
        except WeeklyTest.DoesNotExist:
            return Response(data={'info':'test not found'}, status=status.HTTP_404_NOT_FOUND)
    dataset = {}
    for l_test in live_tests:
        unit_data = {}
        unit_data['issued'] = l_test.num_answer_sheets
        unit_data['submitted'] = l_test.num_submitted_answer_sheets
        dataset[l_test.id] = unit_data
    live_test_data = {'lt_data':dataset}
    return Response(data=live_test_data, status=status.HTTP_200_OK)
    



@api_view(["POST"])
@permission_classes([IsAuthenticated])
def update_score(request, answersheet_pk):
    answersheet = get_object_or_404(AnswerSheet, pk=answersheet_pk)
    if request.user not in answersheet.test.weekly.classroom.teachers.all():
        return Response(status=status.HTTP_403_FORBIDDEN)
    for ans_dat in request.data:
        des_ans = get_object_or_404(DescriptiveAnswer, pk=ans_dat['pk'], answer_sheet=answersheet)
        des_ans.score = ans_dat['score']
        des_ans.save()
    return Response(data={'status':'score updated'},status=status.HTTP_202_ACCEPTED)



class TestAnswersheetsView(ListAPIView):
    serializer_class = AnswerSheetSerializer
    permission_classes = [IsAuthenticated & IsUserTeacherOfClassroom]
    pagination_class = AnswerSheetPagination
    def get_object(self):
        pk = self.kwargs.get('pk')
        test =  get_object_or_404(WeeklyTest, pk=pk) 
        self.check_object_permissions(self.request, test)
        return test
    def get_queryset(self):
        test = self.get_object()
        answer_sheets = AnswerSheet.objects.filter(test=test, submit_time__isnull=False).order_by('submit_time')
        answer_sheets_sorted = sorted(answer_sheets, key=lambda o: o.time_taken)
        return answer_sheets_sorted

weekly_test/templates/weekly_test/exam_delete.html
{% extends 'classroom/base.html' %}
{% block style %} {% load static %}
<link rel="stylesheet" href="{% static 'classroom/styles/navbar.css' %}">
<link rel="stylesheet" href="{% static 'classroom/styles/edit_post.css' %}">
{% endblock style %}
{% block title %}<title>Delete Test</title>{% endblock title %}
{% block nav %}
<ul class="navbar-nav mb-2 mb-lg-0">
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="{% url 'classroom:classroom_detail' weeklytest.weekly.classroom.id %}">Dashboard</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_connections' weeklytest.weekly.classroom.id %}">Participants</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_ranking'  weeklytest.weekly.classroom.id %}">Ranking</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:view_assessment' weeklytest.weekly.classroom.id %}">Assessment</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_about' weeklytest.weekly.classroom.id %}">About</a>
  </li>
</ul>
{% endblock nav %}


{% block content %}
<div class="delete-post">
  <div class="home-links">
    <a href="">Classroom Name</a>
  </div>
  <div class="info-con shadow-lg">
    <i class='bg bx bx-message-x'></i>
    <div class="info-text">You're about to delete this test and all the data associated with it!</div>
  </div>
  <div class="action">
    <a href="{% url 'weekly_test:view_test' weeklytest.id %}" class="ico-btn btn btn-secondary"><i class='bx bx-chevrons-left'></i><span>Go Back</span></a>
    <button href="#" class="ico-btn btn btn-danger" id="test-del-btn"><i class='bx bx-trash-alt'></i><span>Delete</span></button>
  </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'weekly_test/scripts/delete_test.js' %}"></script>
<script>
  const delete_test_api_url = "{% url 'weekly_test_api:delete_test' weeklytest.id %}"
  const clssroom_url = "{% url 'classroom:classroom_detail' weeklytest.weekly.classroom.id %}"
  let csrftoken = "{{ csrf_token }}"
</script>
{% endblock script %}

weekly_test/templates/weekly_test/home.html
<h1>Homepage</h1>
<ul>
    {% for test in tests %}
    <li><a href="{% url 'take_test' test.id %}">{{ test.title }}</a></li>
    {% endfor %}
</ul>

weekly_test/templates/weekly_test/view_answersheet.html
{% extends 'classroom/base.html' %}
{% block style %} {% load static %}
<link rel="stylesheet" href="{% static 'weekly_test/styles/view_answersheet.css' %}">
<link rel="stylesheet" href="{% static 'classroom/styles/navbar.css' %}">
{% endblock style %}
{% block title %}<title>Answersheet</title>{% endblock title %}
{% block nav %}
<ul class="navbar-nav mb-2 mb-lg-0">
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="{% url 'classroom:classroom_detail' answersheet.test.weekly.classroom.id %}">Dashboard</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_connections' answersheet.test.weekly.classroom.id %}">Participants</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_ranking' answersheet.test.weekly.classroom.id %}">Ranking</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:view_assessment' answersheet.test.weekly.classroom.id %}">Assessment</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'classroom:classroom_about' answersheet.test.weekly.classroom.id %}">About</a>
  </li>
</ul>
{% endblock nav %}

{% block content %}
<div class="view-submission-container">
  <div class="info">
    <div class="home-links">
      <a href="{% url 'classroom:classroom_detail' answersheet.test.weekly.classroom.id %}">{{answersheet.test.weekly.classroom.name|truncatechars:10}}</a>
      <i class='bx bxs-chevron-right'></i>
      <a href="{% url 'weeklies:weeklydetail' answersheet.test.weekly.classroom.id answersheet.test.weekly.weeknum %}">Week {{answersheet.test.weekly.weeknum}}</a>
      <i class='bx bxs-chevron-right'></i>
      <a href="{% url 'weekly_test:view_test' answersheet.test.id %}" class="current">{{answersheet.test.weekly_section}} Test</a>
    </div>
    <div class="score-card">
      <div class="obtained-points">
        {% if answersheet.total_score is none %}
        <div class="score-none">
          <i class='bx bx-info-circle'></i>
          <span>Result Pending</span>
        </div>
        {% else %}
        <div class="score-con">
          <i class='bx bx-trophy'></i>
          <div class="points">Score:<span class="point">{{answersheet.get_score}}</span></div>
        </div>
        {% endif %}
      </div>
      <div class="task-points"><span class="num-points">{{answersheet.test.total_marks}}</span></div>
    </div>
    <div class="task-title">{{answersheet.test.title}}</div>
    
    <div class="test-time">
      <div class="time-info">
        <span class="label">Started at:</span>
        <span class="time" id="as-{{answersheet.id}}-start">{{answersheet.issue_time|date:"c"}}</span>
      </div>
      <div class="time-info">
        <span class="label">Submitted at:</span>
        <span class="time" id="as-{{answersheet.id}}-submit">{{answersheet.submit_time|date:"c"}}</span>
      </div>
    </div>
  </div>
  <div class="bottom-pane">
    <div class="submitted-contents">
      <div class="title"><i class='bx bx-file'></i><span>Submitted Answers</span></div>
      {% if request.user in answersheet.test.weekly.classroom.teachers.all %}
      <div class="answers-container">
        {% for des_ans in answersheet.answers.des_answers %}
        {% if des_ans.question.ans_as_img %}
        <div class="q qtype-image">
          <div class="qno-count-container">
              <div class="qno-count-inner">
                  <div class="label">SN</div>
                  <div class="qno-count" id="aid_{{des_ans.id}}-count">-</div>
              </div>
              <div class="qtype-info">DESCRIPTIVE</div>
          </div>
          <div class="content">
              <div class="meta">
                <div class="q-title"><span class="label">Statement:</span>{{des_ans.question.statement}}</div>
                <div class="a-score inset-float-textinput">
                  <input type="text" class="q-marks-input" id="desid_{{des_ans.id}}-marks" data-q-marks="{{des_ans.question.get_mark}}" data-ans-id="{{des_ans.id}}" {% if des_ans.has_score %}value={{des_ans.get_score}}{% endif %}>
                  <label for="qid_{{des_ans.id}}-marks">Score - out of <span class="marks">{{des_ans.question.get_mark}}</span></label>
                </div>
              </div>
              <div class="ans-img">
                {% if des_ans.has_viewable_file %}
                <embed src="{{des_ans.answer_img.url}}" style="width: 100%; min-height:25rem;" type="">
                {% else %}
                <div class="invalid-file-format-info py-3">
                  <div class="infotext mb-3">This file is not supported to view!</div>
                  <div class="download-btn-con">
                    <a href="{{des_ans.answer_img.url}}"><i class='bx bx-download'></i><span>Download</span></a>
                  </div>
                </div>
                {% endif %}
              </div>
          </div>
        </div>
        {% else %}
        <div class="q qtype-text">
            <div class="qno-count-container">
              <div class="qno-count-inner">
                  <div class="label">SN</div>
                  <div class="qno-count" id="aid_{{des_ans.id}}-count">-</div>
              </div>
              <div class="qtype-info">DESCRIPTIVE</div>
          </div>
          <div class="content">
              <div class="meta">
                <div class="q-title"><span class="label">Statement:</span>{{des_ans.question.statement}}</div>
                <div class="a-score inset-float-textinput">
                  <input type="text" class="q-marks-input" id="desid_{{des_ans.id}}-marks" data-q-marks="{{des_ans.question.get_mark}}"  data-ans-id="{{des_ans.id}}" {% if des_ans.has_score %}value={{des_ans.get_score}}{% endif %}>
                  <label for="qid_{{des_ans.id}}-marks">Score - out of <span class="marks">{{des_ans.question.get_mark}}</span></label>
                </div>
              </div>
              <div class="ans-text" alt="Answer">{{des_ans.answer_text}}</div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
        {% for mcq_ans in answersheet.answers.mcq_answers %}
        <div class="q qtype-mcq" id="qid_1">
          <div class="qno-count-container">
              <div class="qno-count-inner">
                <div class="label">SN</div>
                <div class="qno-count" id="mcqid_{{mcq_ans.id}}-count">-</div>
              </div>
              <div class="qtype-info">MCQ</div>
          </div>
          <div class="content">
              <div class="meta">
                <div class="q-title" id="mcqid_{{mcq_ans.id}}-title"><span class="label">Statement:</span>{{mcq_ans.question.statement}}</div>
                <div class="score-container">
                  {% if mcq_ans.is_correct_ans %}
                  <span class="correct">Correct<span class="score">{{mcq_ans.question.get_mark}}/{{mcq_ans.question.get_mark}}</span></span>
                  {% else %}
                  <span class="incorrect">Incorrect<span class="score">0/{{mcq_ans.question.get_mark}}</span></span>
                  {% endif %}
                </div>
              </div>
              {% for option in mcq_ans.options_data %}
              <div class="choice-container">
                <input type="radio" class="{{option.css_class}}" disabled="disabled">
                <label>{{option.choice_code}}</label>
                <div class="choice-text">{{option.option_text}}</div>
              </div>
              {% endfor %}
          </div>
        </div>
        {% endfor %}
        {% if answersheet.num_des_answers %}
        <div class="submit-container">
          <button type="submit" id="save-score_btn">Save</button>
        </div>
        {% endif %}
      </div>
      {% else %}
      <div class="answers-container">
        {% for des_ans in answersheet.answers.des_answers %}
        {% if des_ans.question.ans_as_img %}
        <div class="q qtype-image">
          <div class="qno-count-container">
              <div class="qno-count-inner">
                  <div class="label">SN</div>
                  <div class="qno-count" id="aid_{{des_ans.id}}-count">-</div>
              </div>
              <div class="qtype-info">DESCRIPTIVE</div>
          </div>
          <div class="content">
              <div class="meta">
                <div class="q-title"><span class="label">Statement:</span>{{des_ans.question.statement}}</div>
                <div class="user-score-info">
                  {% if des_ans.has_score %}
                  <div class="score-container">
                    <span class="label">Score</span>
                    <span class="my-score">{{des_ans.get_score}} / {{des_ans.question.get_mark}}</span>
                  </div>
                  {% else %}
                  <div class="unchecked">
                    <span class="ans-info">Unchecked</span>
                  </div>
                  {% endif %}
                </div>
              </div>
              <div class="ans-img">
                  {% if des_ans.has_viewable_file %}
                  <embed src="{{des_ans.answer_img.url}}" style="width: 100%; min-height:25rem;" type="">
                  {% else %}
                  <div class="invalid-file-format-info py-3">
                    <div class="infotext mb-3">This file is not supported to view!</div>
                    <div class="download-btn-con">
                      <a href="{{des_ans.answer_img.url}}"><i class='bx bx-download'></i><span>Download</span></a>
                    </div>
                  </div>
                  {% endif %}
              </div>
          </div>
        </div>
        {% else %}
        <div class="q qtype-text">
            <div class="qno-count-container">
              <div class="qno-count-inner">
                  <div class="label">SN</div>
                  <div class="qno-count" id="aid_{{des_ans.id}}-count">-</div>
              </div>
              <div class="qtype-info">DESCRIPTIVE</div>
          </div>
          <div class="content">
              <div class="meta">
                <div class="q-title"><span class="label">Statement:</span>{{des_ans.question.statement}}</div>
                <div class="user-score-info">
                  {% if des_ans.has_score %}
                  <div class="score-container">
                    <span class="label">Score</span>
                    <span class="my-score">{{des_ans.get_score}} / {{des_ans.question.get_mark}}</span>
                  </div>
                  {% else %}
                  <div class="unchecked">
                    <span class="ans-info">Unchecked</span>
                  </div>
                  {% endif %}
                </div>
              </div>
              <div class="ans-text" alt="Answer">{{des_ans.answer_text}}</div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
        {% for mcq_ans in answersheet.answers.mcq_answers %}
        <div class="q qtype-mcq" id="qid_1">
          <div class="qno-count-container">
              <div class="qno-count-inner">
                <div class="label">SN</div>
                <div class="qno-count" id="mcqid_{{mcq_ans.id}}-count">-</div>
              </div>
              <div class="qtype-info">MCQ</div>
          </div>
          <div class="content">
              <div class="meta">
                <div class="q-title" id="mcqid_{{mcq_ans.id}}-title"><span class="label">Statement:</span>{{mcq_ans.question.statement}}</div>
                <div class="score-container">
                  {% if mcq_ans.is_correct_ans %}
                  <span class="correct">Correct<span class="score">{{mcq_ans.question.get_mark}}/{{mcq_ans.question.get_mark}}</span></span>
                  {% else %}
                  <span class="incorrect">Incorrect<span class="score">0/{{mcq_ans.question.get_mark}}</span></span>
                  {% endif %}
                </div>
              </div>
              {% for option in mcq_ans.options_data %}
              <div class="choice-container">
                <input type="radio" class="{{option.css_class}}" disabled="disabled">
                <label>{{option.choice_code}}</label>
                <div class="choice-text">{{option.option_text}}</div>
              </div>
              {% endfor %}
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
      
    </div>
    <div class="submitting-student">
      <div class="title">Examinee</div>
      <div class="user">
        <div class="dp" style="background-image: url('{{answersheet.user.account.avatar_url}}');"></div>
        <div class="name">{{answersheet.user.account.user_full_name}}</div>
        <div class="inst-id">{{answersheet.user.account.institutional_id}}</div>
        <div class="inst">{{answersheet.user.account.institution}}</div>
      </div>
    </div>
  </div>

</div>
{% endblock content %}

{% block script %}
<script src="{% static 'classroom/scripts/localtimes.js' %}"></script>
<script src="{% static 'weekly_test/scripts/view_answersheet.js' %}"></script>
<script>
  const update_score_url = "{% url 'weekly_test_api:update_score' answersheet.id %}"
  const csrftoken = "{{csrf_token}}"
</script>
{% endblock script %}